const names={dashboard:'Nadzorna ploča',projects:'Gradilišta',incoming:'Ulazna pošta',outgoing:'Izlazna pošta',offers:'Ponude',incomingInvoices:'Ulazni računi',invoices:'Fakture',cash:'Blagajne',journal:'Izravno knjiženje',ledger:'Izvod konta',assets:'Osnovna sredstva',vat:'PDV prijava',gl:'Glavna knjiga',bank:'Bankovni izvodi',payments:'Nalozi za plaćanje',employees:'Zaposlenici',candidates:'Kandidati',leave:'Godišnji odmori',hours:'Radni sati',payroll:'Obračun plaća',joppd:'JOPPD obrasci',contracts:'Ugovori',companyDocs:'Dokumentacija firme',orders:'Narudžbenice',items:'Artikli'};
const employees=[{id:1,name:'Ivan Horvat',role:'Monter suhe gradnje',project:'Kuća Čolak',email:'ivan.horvat@demo.hr',phone:'+385 91 222 3344',start:'10.02.2025',salary:'1.650 € bruto'},{id:2,name:'Marko Kovač',role:'Soboslikar',project:'Pajić-Amerikanac',email:'marko.kovac@demo.hr',phone:'+385 98 444 2291',start:'03.06.2024',salary:'1.590 € bruto'},{id:3,name:'Arben D.',role:'Knauf monter',project:'VERTIV',email:'arben@demo.hr',phone:'+385 99 112 0988',start:'10.08.2026',salary:'Satnica 11,50 €'},{id:4,name:'Petar Marić',role:'Voditelj gradilišta',project:'Vinkovićeva 3',email:'petar.maric@demo.hr',phone:'+385 91 777 6312',start:'14.01.2023',salary:'2.100 € bruto'}];
const content=document.getElementById('content'),title=document.getElementById('title');
const gate=document.getElementById('companyGate'),shell=document.getElementById('appShell');
function setGateDate(){const d=new Date();document.getElementById('gateDate').textContent=d.toLocaleDateString('hr-HR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).toUpperCase()}
function openCompany(){gate.style.display='none';shell.classList.remove('app-hidden');show('dashboard');window.scrollTo(0,0)}
function backToCompanies(){shell.classList.add('app-hidden');gate.style.display='flex';window.scrollTo(0,0)}
setGateDate();
document.getElementById('companySearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.company-card').forEach(c=>c.style.display=c.dataset.company.includes(q)?'block':'none')});
document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>b.nextElementSibling.classList.toggle('open'));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
function show(v){title.textContent=names[v]||v;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='dashboard')dashboard();else if(v==='projects')projects();else if(v==='employees')employeesView();else generic(v)}
function dashboard(){content.innerHTML=`<div class="hero"><div><h2>Kontrola poslovanja u jednom pogledu</h2><p>Tasker izgled, poslovna logika po uzoru na iSKAP. Svi podaci su demo.</p></div><div class="chip">● SUSTAV AKTIVAN</div></div><div class="grid kpis">${kpi('Aktivna gradilišta','7','+2 ovaj mjesec')}${kpi('Zaposlenici danas','34','31 evidentirano')}${kpi('Trošak mjeseca','84.290 €','+6,4% prema prošlom')}${kpi('Rezultat mjeseca','+21.740 €','pozitivan rezultat')}</div><div class="grid split"><div class="card"><div class="section-title"><h3>Aktivna gradilišta</h3><button class="btn secondary" onclick="show('projects')">Prikaži sva</button></div>${project('Kuća Čolak','35.730 € trošak • 46.000 € fakturirano',78)}${project('Pajić-Amerikanac','18.260 € trošak • 27.800 € fakturirano',61)}${project('VERTIV','42.190 € trošak • 58.500 € fakturirano',84)}</div><div class="card"><div class="section-title"><h3>Upozorenja</h3><span class="muted">Danas</span></div><div class="alert"><b>3 računa čekaju ovjeru</b><br><small>Ukupno 4.290 €</small></div><div class="alert"><b>2 dokumenta uskoro istječu</b><br><small>Rok unutar 30 dana</small></div><div class="alert"><b>1 narudžbenica nije isporučena</b><br><small>Kuća Čolak</small></div></div></div>`}
function kpi(a,b,c){return `<div class="card kpi"><label>${a}</label><strong>${b}</strong><small>${c}</small></div>`}function project(a,b,p){return `<div class="project"><div class="project-head"><div><b>${a}</b><br><small>${b}</small></div><b>${p}%</b></div><div class="progress"><span style="width:${p}%"></span></div></div>`}
function projects(){content.innerHTML=`<div class="toolbar"><div class="filters"><button class="filter">Aktivni</button><button class="filter">Isporučeno</button><button class="filter">Arhiva</button></div><button class="btn">+ Novo gradilište</button></div><div class="card table-card"><table><thead><tr><th>Projekt</th><th>Status</th><th>Početak</th><th>Radnici</th><th>Trošak</th><th>Fakturirano</th><th>Rezultat</th></tr></thead><tbody>${prow('Kuća Čolak','Aktivan','12.03.2026','8','35.730 €','46.000 €','+10.270 €')}${prow('Pajić-Amerikanac','Aktivan','04.05.2026','6','18.260 €','27.800 €','+9.540 €')}${prow('VERTIV','Aktivan','10.01.2026','12','42.190 €','58.500 €','+16.310 €')}${prow('Vinkovićeva 3','Isporučeno','08.02.2026','5','28.410 €','36.200 €','+7.790 €')}</tbody></table></div>`}function prow(a,b,c,d,e,f,g){return `<tr><td><b>${a}</b></td><td>${pill(b,b==='Aktivan'?'green':'blue')}</td><td>${c}</td><td>${d}</td><td>${e}</td><td>${f}</td><td><b>${g}</b></td></tr>`}
function employeesView(){content.innerHTML=`<div class="employee-layout"><div class="card employee-list"><div class="section-title"><h3>Zaposlenici</h3><button class="btn">+</button></div>${employees.map((e,i)=>`<div class="employee-row ${i===0?'active':''}" onclick="employee(${e.id},this)"><div class="emp-avatar">${init(e.name)}</div><div><b>${e.name}</b><small>${e.role} • ${e.project}</small></div></div>`).join('')}</div><div class="card" id="profile"></div></div>`;employee(1)}
function init(n){return n.split(' ').slice(0,2).map(x=>x[0]).join('')}function employee(id,el){if(el){document.querySelectorAll('.employee-row').forEach(x=>x.classList.remove('active'));el.classList.add('active')}const e=employees.find(x=>x.id===id);document.getElementById('profile').innerHTML=`<div class="profile-head"><div class="profile-id"><div class="profile-avatar">${init(e.name)}</div><div><h2>${e.name}</h2><p>${e.role}</p><p>${pill('Aktivan','green')} &nbsp; ${e.project}</p></div></div><button class="btn secondary">Otvori karton</button></div><div class="tabs">${['Osobni podaci','Ugovori','Status','Dokumenti','Vještine','Obitelj','Bankovni računi','Odjeća','Plaća','Ocjene','Blagajna'].map((t,i)=>`<button class="tab ${i===0?'active':''}" onclick="tab(this,'${t}',${id})">${t}</button>`).join('')}</div><div id="tabBody">${personal(e)}</div>`}
function personal(e){return `<div class="details">${detail('Ime i prezime',e.name)}${detail('Radno mjesto',e.role)}${detail('Poslovna jedinica',e.project)}${detail('Datum početka',e.start)}${detail('E-mail',e.email)}${detail('Telefon',e.phone)}${detail('OIB','*** DEMO ***')}${detail('Plaća / satnica',e.salary)}</div>`}function detail(a,b){return `<div class="detail"><label>${a}</label><b>${b}</b></div>`}
function tab(btn,t,id){btn.parentElement.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const e=employees.find(x=>x.id===id),m={'Osobni podaci':personal(e),'Ugovori':mini(['Vrsta','Od','Do','Radno mjesto','Bruto'],[['Ugovor o radu',e.start,'—',e.role,e.salary]]),'Status':mini(['Datum','Status','Gradilište'],[['18.08.2026','Redovan rad',e.project],['17.08.2026','Redovan rad',e.project]]),'Dokumenti':mini(['Dokument','Datum','Vrijedi do','Status'],[['Ugovor o radu',e.start,'—','Važeći'],['Zaštita na radu','10.02.2026','10.02.2027','Važeći']]),'Vještine':mini(['Vještina','Razina'],[['Knauf','5 / 5'],['Gletanje','4 / 5'],['Farbanje','4 / 5']]),'Obitelj':mini(['Ime','Odnos','Kontakt'],[['Demo kontakt','Kontakt za hitnoću','+385 91 000 0000']]),'Bankovni računi':mini(['Banka','IBAN','Status'],[['Demo banka','HRxx **** **** **** **** *','Aktivan']]),'Odjeća':mini(['Stavka','Veličina'],[['Majica','XL'],['Hlače','54'],['Obuća','44']]),'Plaća':mini(['Razdoblje','Osnovica','Dodaci','Isplata'],[['07/2026',e.salary,'120 €','Isplaćeno']]),'Ocjene':mini(['Datum','Ocjena','Napomena'],[['01.08.2026','4.7 / 5','Pouzdan rad']]),'Blagajna':mini(['Datum','Vrsta','Iznos','Opis'],[['02.08.2026','Predujam','200 €','Terenski trošak']])};document.getElementById('tabBody').innerHTML=m[t]}
function mini(h,r){return `<div class="table-card"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.map(a=>`<tr>${a.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}function pill(t,c){return `<span class="status ${c}">${t}</span>`}
function generic(v){const data={incomingInvoices:[['UR-2026-0812','Ovjera','Bačelić','18.08.2026','1.284,40 €','Kuća Čolak'],['UR-2026-0811','Na knjiženju','Demo dobavljač','17.08.2026','642,90 €','VERTIV']],invoices:[['IR-2026-102','Poslano','Demo investitor','18.08.2026','7.800,00 €','Pajić-Amerikanac']],orders:[['N-2026-214','Zaključeno','Bačelić','18.08.2026','1.042,00 €','Kuća Čolak']],hours:[['08/2026','Zaključeno','Kuća Čolak','18.08.2026','1.284 h','8 radnika']],payroll:[['07/2026','Zaključeno','Obračun plaća','31.07.2026','34 osobe','Izvorni']]}[v]||[['EV-2026-001','Aktivan',names[v]||v,'18.08.2026','Demo podatak','—'],['EV-2026-002','Zaključeno',names[v]||v,'17.08.2026','Demo podatak','—']];content.innerHTML=`<div class="toolbar"><div class="filters"><button class="filter">Pretraga</button><button class="filter">Status</button><button class="filter">Razdoblje</button><button class="filter">Excel</button></div><button class="btn">+ Novi zapis</button></div><div class="card table-card"><table><thead><tr><th>Ev. br.</th><th>Status</th><th>Naziv / Partner</th><th>Datum</th><th>Vrijednost</th><th>Projekt / Napomena</th></tr></thead><tbody>${data.map(r=>`<tr>${r.map((x,i)=>`<td>${i===1?pill(x,x==='Aktivan'?'green':x==='Ovjera'?'yellow':'blue'):x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}