const names={dashboard:'Nadzorna ploča',projects:'Gradilišta',incoming:'Ulazna pošta',outgoing:'Izlazna pošta',offers:'Ponude',incomingInvoices:'Ulazni računi',invoices:'Fakture',cash:'Blagajne',journal:'Izravno knjiženje',ledger:'Izvod konta',assets:'Osnovna sredstva',vat:'PDV prijava',gl:'Glavna knjiga',bank:'Bankovni izvodi',payments:'Nalozi za plaćanje',employees:'Zaposlenici',candidates:'Kandidati',leave:'Godišnji odmori',hours:'Radni sati',payroll:'Obračun plaća',joppd:'JOPPD obrasci',contracts:'Ugovori',companyDocs:'Dokumentacija firme',orders:'Narudžbenice',items:'Artikli',reports:'Izvještaji',approvals:'Ovjera',partners:'Partneri',delivery:'Dostava dokumenata'};
const employees=[{id:1,name:'Ivan Horvat',role:'Monter suhe gradnje',project:'Kuća Čolak',email:'ivan.horvat@demo.hr',phone:'+385 91 222 3344',start:'10.02.2025',salary:'1.650 € bruto'},{id:2,name:'Marko Kovač',role:'Soboslikar',project:'Pajić-Amerikanac',email:'marko.kovac@demo.hr',phone:'+385 98 444 2291',start:'03.06.2024',salary:'1.590 € bruto'},{id:3,name:'Arben D.',role:'Knauf monter',project:'VERTIV',email:'arben@demo.hr',phone:'+385 99 112 0988',start:'10.08.2026',salary:'Satnica 11,50 €'},{id:4,name:'Petar Marić',role:'Voditelj gradilišta',project:'Vinkovićeva 3',email:'petar.maric@demo.hr',phone:'+385 91 777 6312',start:'14.01.2023',salary:'2.100 € bruto'}];
const projectsData=[{name:'Kuća Čolak',status:'Aktivan',start:'12.03.2026',workers:8,cost:'35.730 €',billed:'46.000 €',result:'+10.270 €',progress:78},{name:'Pajić-Amerikanac',status:'Aktivan',start:'04.05.2026',workers:6,cost:'18.260 €',billed:'27.800 €',result:'+9.540 €',progress:61},{name:'VERTIV',status:'Aktivan',start:'10.01.2026',workers:12,cost:'42.190 €',billed:'58.500 €',result:'+16.310 €',progress:84},{name:'Vinkovićeva 3',status:'Isporučeno',start:'08.02.2026',workers:5,cost:'28.410 €',billed:'36.200 €',result:'+7.790 €',progress:100}];
const content=document.getElementById('content'),title=document.getElementById('title');
const gate=document.getElementById('companyGate'),shell=document.getElementById('appShell');
function setGateDate(){const d=new Date();document.getElementById('gateDate').textContent=d.toLocaleDateString('hr-HR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).toUpperCase()}
function openCompany(){gate.style.display='none';shell.classList.remove('app-hidden');show('dashboard');window.scrollTo(0,0)}
function backToCompanies(){shell.classList.add('app-hidden');gate.style.display='flex';window.scrollTo(0,0)}
setGateDate();
document.getElementById('companySearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.company-card').forEach(c=>c.style.display=c.dataset.company.includes(q)?'block':'none')});
document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>b.nextElementSibling.classList.toggle('open'));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
function show(v){title.textContent=names[v]||v;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='dashboard')dashboard();else if(v==='projects')projects();else if(v==='employees')employeesView();else if(v==='reports')reportsView();else if(v==='approvals')approvalsView();else if(v==='partners')partnersView();else if(v==='delivery')deliveryView();else generic(v)}
function dashboard(){content.innerHTML=`<div class="hero clickable-card" onclick="show('reports')"><div><h2>Kontrola poslovanja u jednom pogledu</h2><p>Tasker izgled, poslovna logika po uzoru na iSKAP. Svi podaci su demo.</p></div><div class="chip">● SUSTAV AKTIVAN</div></div><div class="grid kpis">${kpi('Aktivna gradilišta','7','+2 ovaj mjesec','projects')}${kpi('Zaposlenici danas','34','31 evidentirano','employees')}${kpi('Trošak mjeseca','84.290 €','+6,4% prema prošlom','incomingInvoices')}${kpi('Rezultat mjeseca','+21.740 €','pozitivan rezultat','invoices')}</div><div class="grid split"><div class="card"><div class="section-title"><h3>Aktivna gradilišta</h3><button class="btn secondary" onclick="event.stopPropagation();show('projects')">Prikaži sva</button></div>${projectCard(projectsData[0])}${projectCard(projectsData[1])}${projectCard(projectsData[2])}</div><div class="card"><div class="section-title"><h3>Upozorenja</h3><span class="muted">Danas</span></div>${alertCard('3 računa čekaju ovjeru','Ukupno 4.290 €','approvals')}${alertCard('2 dokumenta uskoro istječu','Rok unutar 30 dana','companyDocs')}${alertCard('1 narudžbenica nije isporučena','Kuća Čolak','orders')}</div></div>`}
function kpi(a,b,c,target){return `<button class="card kpi dashboard-card" onclick="show('${target}')"><label>${a}</label><strong>${b}</strong><small>${c}</small><span class="card-arrow">→</span></button>`}
function projectCard(p){return `<button class="project project-click" onclick="openProjectDetail('${p.name.replace(/'/g,"\\'")}')"><div class="project-head"><div><b>${p.name}</b><br><small>${p.cost} trošak • ${p.billed} fakturirano</small></div><b>${p.progress}%</b></div><div class="progress"><span style="width:${p.progress}%"></span></div><div class="project-open">Otvori projekt →</div></button>`}
function alertCard(a,b,target){return `<button class="alert alert-click" onclick="show('${target}')"><b>${a}</b><br><small>${b}</small><span>→</span></button>`}
function openProjectDetail(name){const p=projectsData.find(x=>x.name===name);if(!p)return;title.textContent=p.name;content.innerHTML=`<div class="toolbar"><button class="filter" onclick="show('dashboard')">← Nadzorna ploča</button><button class="btn" onclick="show('projects')">Sva gradilišta</button></div><div class="hero"><div><h2>${p.name}</h2><p>Status: ${p.status} • Početak: ${p.start}</p></div><div class="chip">${p.progress}% ZAVRŠENO</div></div><div class="grid kpis">${detailKpi('Radnici',p.workers)}${detailKpi('Trošak',p.cost)}${detailKpi('Fakturirano',p.billed)}${detailKpi('Rezultat',p.result)}</div><div class="grid split"><div class="card"><div class="section-title"><h3>Pregled projekta</h3></div>${mini(['Podatak','Vrijednost'],[['Naziv',p.name],['Status',p.status],['Datum početka',p.start],['Broj radnika',String(p.workers)],['Napredak',p.progress+'%']])}</div><div class="card"><div class="section-title"><h3>Brze akcije</h3></div><button class="btn quick-action" onclick="show('hours')">Radni sati</button><button class="btn secondary quick-action" onclick="show('orders')">Narudžbenice</button><button class="btn secondary quick-action" onclick="show('invoices')">Fakture</button><button class="btn secondary quick-action" onclick="show('companyDocs')">Dokumentacija</button></div></div>`}
function detailKpi(a,b){return `<div class="card kpi"><label>${a}</label><strong>${b}</strong></div>`}
function projects(){content.innerHTML=`<div class="toolbar"><div class="filters"><button class="filter">Aktivni</button><button class="filter">Isporučeno</button><button class="filter">Arhiva</button></div><button class="btn">+ Novo gradilište</button></div><div class="card table-card"><table><thead><tr><th>Projekt</th><th>Status</th><th>Početak</th><th>Radnici</th><th>Trošak</th><th>Fakturirano</th><th>Rezultat</th></tr></thead><tbody>${projectsData.map(p=>`<tr class="table-link" onclick="openProjectDetail('${p.name.replace(/'/g,"\\'")}')"><td><b>${p.name}</b></td><td>${pill(p.status,p.status==='Aktivan'?'green':'blue')}</td><td>${p.start}</td><td>${p.workers}</td><td>${p.cost}</td><td>${p.billed}</td><td><b>${p.result}</b></td></tr>`).join('')}</tbody></table></div>`}
function employeesView(){content.innerHTML=`<div class="employee-layout"><div class="card employee-list"><div class="section-title"><h3>Zaposlenici</h3><button class="btn">+</button></div>${employees.map((e,i)=>`<div class="employee-row ${i===0?'active':''}" onclick="employee(${e.id},this)"><div class="emp-avatar">${init(e.name)}</div><div><b>${e.name}</b><small>${e.role} • ${e.project}</small></div></div>`).join('')}</div><div class="card" id="profile"></div></div>`;employee(1)}
function init(n){return n.split(' ').slice(0,2).map(x=>x[0]).join('')}
function employee(id,el){if(el){document.querySelectorAll('.employee-row').forEach(x=>x.classList.remove('active'));el.classList.add('active')}const e=employees.find(x=>x.id===id);document.getElementById('profile').innerHTML=`<div class="profile-head"><div class="profile-id"><div class="profile-avatar">${init(e.name)}</div><div><h2>${e.name}</h2><p>${e.role}</p><p>${pill('Aktivan','green')} &nbsp; ${e.project}</p></div></div><button class="btn secondary" onclick="tab(document.querySelector('.tab'),'Osobni podaci',${id})">Otvori karton</button></div><div class="tabs">${['Osobni podaci','Ugovori','Status','Dokumenti','Vještine','Obitelj','Bankovni računi','Odjeća','Plaća','Ocjene','Blagajna'].map((t,i)=>`<button class="tab ${i===0?'active':''}" onclick="tab(this,'${t}',${id})">${t}</button>`).join('')}</div><div id="tabBody">${personal(e)}</div>`}
function personal(e){return `<div class="details">${detail('Ime i prezime',e.name)}${detail('Radno mjesto',e.role)}${detail('Poslovna jedinica',e.project)}${detail('Datum početka',e.start)}${detail('E-mail',e.email)}${detail('Telefon',e.phone)}${detail('OIB','*** DEMO ***')}${detail('Plaća / satnica',e.salary)}</div>`}
function detail(a,b){return `<div class="detail"><label>${a}</label><b>${b}</b></div>`}
function tab(btn,t,id){if(btn&&btn.parentElement){btn.parentElement.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}const e=employees.find(x=>x.id===id),m={'Osobni podaci':personal(e),'Ugovori':mini(['Vrsta','Od','Do','Radno mjesto','Bruto'],[['Ugovor o radu',e.start,'—',e.role,e.salary]]),'Status':mini(['Datum','Status','Gradilište'],[['18.08.2026','Redovan rad',e.project],['17.08.2026','Redovan rad',e.project]]),'Dokumenti':mini(['Dokument','Datum','Vrijedi do','Status'],[['Ugovor o radu',e.start,'—','Važeći'],['Zaštita na radu','10.02.2026','10.02.2027','Važeći']]),'Vještine':mini(['Vještina','Razina'],[['Knauf','5 / 5'],['Gletanje','4 / 5'],['Farbanje','4 / 5']]),'Obitelj':mini(['Ime','Odnos','Kontakt'],[['Demo kontakt','Kontakt za hitnoću','+385 91 000 0000']]),'Bankovni računi':mini(['Banka','IBAN','Status'],[['Demo banka','HRxx **** **** **** **** *','Aktivan']]),'Odjeća':mini(['Stavka','Veličina'],[['Majica','XL'],['Hlače','54'],['Obuća','44']]),'Plaća':mini(['Razdoblje','Osnovica','Dodaci','Isplata'],[['07/2026',e.salary,'120 €','Isplaćeno']]),'Ocjene':mini(['Datum','Ocjena','Napomena'],[['01.08.2026','4.7 / 5','Pouzdan rad']]),'Blagajna':mini(['Datum','Vrsta','Iznos','Opis'],[['02.08.2026','Predujam','200 €','Terenski trošak']])};document.getElementById('tabBody').innerHTML=m[t]}
function reportsView(){content.innerHTML=`<div class="grid kpis">${kpi('Prihodi','128.400 €','ovaj mjesec','invoices')}${kpi('Troškovi','84.290 €','ovaj mjesec','incomingInvoices')}${kpi('Otvorene obveze','17.820 €','za plaćanje','payments')}${kpi('Radni sati','5.482 h','ovaj mjesec','hours')}</div><div class="card table-card" style="margin-top:16px">${mini(['Izvještaj','Razdoblje','Status'],[['Bruto bilanca','08/2026','Spremno'],['Izvod konta','08/2026','Spremno'],['Dospjele obveze i potraživanja','08/2026','Spremno'],['Dnevnik knjiženja','08/2026','Spremno']])}</div>`}
function approvalsView(){content.innerHTML=`<div class="toolbar"><div class="filters"><button class="filter">Čeka ovjeru</button><button class="filter">Odobreno</button></div><button class="btn">Osvježi</button></div><div class="card table-card">${mini(['Dokument','Partner','Iznos','Projekt','Status'],[['UR-2026-0812','Bačelić','1.284,40 €','Kuća Čolak','Čeka ovjeru'],['UR-2026-0813','Demo dobavljač','2.180,00 €','VERTIV','Čeka ovjeru'],['UR-2026-0814','Demo servis','825,60 €','Uprava','Čeka ovjeru']])}</div>`}
function partnersView(){content.innerHTML=`<div class="toolbar"><div class="filters"><button class="filter">Kupci</button><button class="filter">Dobavljači</button></div><button class="btn">+ Novi partner</button></div><div class="card table-card">${mini(['Partner','Vrsta','OIB','Kontakt','Status'],[['Bačelić d.o.o.','Dobavljač','***','prodaja@demo.hr','Aktivan'],['LAZZZ d.o.o.','Kupac','***','info@demo.hr','Aktivan'],['VERTIV CROATIA d.o.o.','Kupac','***','office@demo.hr','Aktivan']])}</div>`}
function deliveryView(){content.innerHTML=`<div class="toolbar"><div class="filters"><button class="filter">Novo</button><button class="filter">Obrađeno</button></div><button class="btn">+ Dostavi dokument</button></div><div class="card table-card">${mini(['Dokument','Pošiljatelj','Datum','Vrsta','Status'],[['DOC-2026-031','Tasker d.o.o.','18.08.2026','Račun','Novo'],['DOC-2026-030','Bačelić d.o.o.','17.08.2026','Ponuda','Obrađeno'],['DOC-2026-029','Demo partner','16.08.2026','Ugovor','Obrađeno']])}</div>`}
function mini(h,r){return `<div class="table-card"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.map(a=>`<tr>${a.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function pill(t,c){return `<span class="status ${c}">${t}</span>`}
function generic(v){const data={incomingInvoices:[['UR-2026-0812','Ovjera','Bačelić','18.08.2026','1.284,40 €','Kuća Čolak'],['UR-2026-0811','Na knjiženju','Demo dobavljač','17.08.2026','642,90 €','VERTIV']],invoices:[['IR-2026-102','Poslano','Demo investitor','18.08.2026','7.800,00 €','Pajić-Amerikanac']],orders:[['N-2026-214','Zaključeno','Bačelić','18.08.2026','1.042,00 €','Kuća Čolak']],hours:[['08/2026','Zaključeno','Kuća Čolak','18.08.2026','1.284 h','8 radnika']],payroll:[['07/2026','Zaključeno','Obračun plaća','31.07.2026','34 osobe','Izvorni']],companyDocs:[['DOC-2026-77','Aktivan','Zaštita na radu','18.08.2026','Istječe za 12 dana','Kadrovska']]}[v]||[['EV-2026-001','Aktivan',names[v]||v,'18.08.2026','Demo podatak','—'],['EV-2026-002','Zaključeno',names[v]||v,'17.08.2026','Demo podatak','—']];content.innerHTML=`<div class="toolbar"><div class="filters"><button class="filter">Pretraga</button><button class="filter">Status</button><button class="filter">Razdoblje</button><button class="filter">Excel</button></div><button class="btn">+ Novi zapis</button></div><div class="card table-card"><table><thead><tr><th>Ev. br.</th><th>Status</th><th>Naziv / Partner</th><th>Datum</th><th>Vrijednost</th><th>Projekt / Napomena</th></tr></thead><tbody>${data.map(r=>`<tr>${r.map((x,i)=>`<td>${i===1?pill(x,x==='Aktivan'?'green':x==='Ovjera'?'yellow':'blue'):x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}