(()=>{
const KEY='tasker2_incoming_mail_v1';
const seed=[
{id:'EV-2026-001',status:'Aktivan',partner:'Ulazna pošta',date:'18.08.2026',value:'Demo podatak',note:'—'},
{id:'EV-2026-002',status:'Zaključeno',partner:'Ulazna pošta',date:'17.08.2026',value:'Demo podatak',note:'—'}
];
let rows=[];let search='';let status='Sve';
try{const s=JSON.parse(localStorage.getItem(KEY)||'null');rows=Array.isArray(s)?s:seed}catch(e){rows=seed}
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const save=()=>localStorage.setItem(KEY,JSON.stringify(rows));
const toInput=s=>{const m=String(s||'').match(/^(\d{2})\.(\d{2})\.(\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:''};const fromInput=s=>{if(!s)return'';const a=s.split('-');return `${a[2]}.${a[1]}.${a[0]}`};
function filtered(){const q=search.toLowerCase().trim();return rows.filter(r=>(status==='Sve'||r.status===status)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q)))}
function render(){if($('title'))$('title').textContent='Ulazna pošta';const host=$('content');if(!host)return;host.innerHTML=`<div class="toolbar"><div class="filters"><div class="project-search">⌕ <input id="incomingSearch" placeholder="Pretraži ulaznu poštu..." value="${esc(search)}"></div><select class="filter" id="incomingStatus"><option>Sve</option><option ${status==='Aktivan'?'selected':''}>Aktivan</option><option ${status==='Zaključeno'?'selected':''}>Zaključeno</option></select><button class="filter" id="incomingPeriod">Razdoblje</button><button class="filter" id="incomingExcel">Excel</button></div><button class="btn" id="incomingNew">+ Novi zapis</button></div><div class="card table-card"><table><thead><tr><th>Ev. br.</th><th>Status</th><th>Naziv / Partner</th><th>Datum</th><th>Vrijednost</th><th>Projekt / Napomena</th><th>Akcije</th></tr></thead><tbody id="incomingRows"></tbody></table><div id="incomingEmpty" class="project-empty" hidden>Nema zapisa.</div></div>`;renderRows();$('incomingSearch').oninput=e=>{search=e.target.value;renderRows()};$('incomingStatus').onchange=e=>{status=e.target.value;renderRows()};$('incomingNew').onclick=()=>form();$('incomingPeriod').onclick=()=>alert('Filter razdoblja ćemo povezati s datumima zapisa.');$('incomingExcel').onclick=exportCsv}
function renderRows(){const body=$('incomingRows');if(!body)return;const data=filtered();body.innerHTML=data.map(r=>`<tr class="table-link" data-open="${esc(r.id)}"><td><b>${esc(r.id)}</b></td><td><span class="status ${r.status==='Aktivan'?'green':'blue'}">${esc(r.status)}</span></td><td>${esc(r.partner)}</td><td>${esc(r.date)}</td><td>${esc(r.value)}</td><td>${esc(r.note||'—')}</td><td><div style="display:flex;gap:7px"><button class="project-edit-btn" data-edit="${esc(r.id)}">Uredi</button><button class="project-delete" data-delete="${esc(r.id)}" style="padding:8px 11px">Obriši</button></div></td></tr>`).join('');$('incomingEmpty').hidden=data.length>0;body.onclick=e=>{const d=e.target.closest('[data-delete]');if(d){e.stopPropagation();remove(d.dataset.delete);return}const ed=e.target.closest('[data-edit]');if(ed){e.stopPropagation();form(ed.dataset.edit);return}const tr=e.target.closest('[data-open]');if(tr)form(tr.dataset.open)}}
function remove(id){const r=rows.find(x=>x.id===id);if(!r)return;if(!confirm(`Obrisati zapis ${r.id}?`))return;rows=rows.filter(x=>x.id!==id);save();render()}
function form(id=''){const current=rows.find(x=>x.id===id);const r=current||{id:'EV-'+new Date().getFullYear()+'-'+String(rows.length+1).padStart(3,'0'),status:'Aktivan',partner:'',date:'',value:'',note:''};document.getElementById('incomingOverlay')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="project-overlay" id="incomingOverlay"><div class="project-modal"><div class="project-modal-head"><div><small>${current?'UREĐIVANJE ULAZNE POŠTE':'NOVI ZAPIS'}</small><h3>${current?esc(current.id):'Dodaj ulaznu poštu'}</h3></div><button id="incomingClose">×</button></div><div class="project-form-grid"><label><span>Evidencijski broj *</span><input id="imId" value="${esc(r.id)}"></label><label><span>Status</span><select id="imStatus"><option ${r.status==='Aktivan'?'selected':''}>Aktivan</option><option ${r.status==='Zaključeno'?'selected':''}>Zaključeno</option></select></label><label class="wide"><span>Naziv / Partner *</span><input id="imPartner" value="${esc(r.partner)}"></label><label><span>Datum</span><input id="imDate" type="date" value="${toInput(r.date)}"></label><label><span>Vrijednost</span><input id="imValue" value="${esc(r.value)}"></label><label class="wide"><span>Projekt / Napomena</span><textarea id="imNote" rows="4">${esc(r.note)}</textarea></label></div><div class="project-modal-actions">${current?'<button class="project-delete" id="incomingDelete">Obriši zapis</button>':'<span></span>'}<div><button class="filter" id="incomingCancel">Odustani</button><button class="btn" id="incomingSave">${current?'Sačuvaj promjene':'Dodaj zapis'}</button></div></div></div></div>`);const close=()=>document.getElementById('incomingOverlay')?.remove();$('incomingClose').onclick=close;$('incomingCancel').onclick=close;$('incomingSave').onclick=()=>{const evid=$('imId').value.trim(),partner=$('imPartner').value.trim();if(!evid||!partner){alert('Unesi evidencijski broj i naziv / partnera.');return}if(rows.some(x=>x.id===evid&&x!==current)){alert('Evidencijski broj već postoji.');return}const data={id:evid,status:$('imStatus').value,partner,date:fromInput($('imDate').value),value:$('imValue').value.trim(),note:$('imNote').value.trim()};if(current)Object.assign(current,data);else rows.unshift(data);save();close();render()};if(current)$('incomingDelete').onclick=()=>{close();remove(current.id)}}
function exportCsv(){const data=filtered();const csv=['Ev. br.;Status;Naziv / Partner;Datum;Vrijednost;Projekt / Napomena',...data.map(r=>[r.id,r.status,r.partner,r.date,r.value,r.note].map(x=>'"'+String(x||'').replace(/"/g,'""')+'"').join(';'))].join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ulazna-posta.csv';a.click();URL.revokeObjectURL(a.href)}
window.taskerIncomingView=render;const oldShow=window.show;if(typeof oldShow==='function')window.show=function(v){if(v==='incoming')return render();return oldShow(v)};document.addEventListener('click',e=>{if(e.target.closest('[data-view="incoming"]'))setTimeout(render,0)});
})();