(()=>{
const CFG={
outgoing:{t:'Izlazna pošta',n:'Nova pošta',p:'IP',s:['U izradi','Poslano','Zaključeno'],c:[['type','Vrsta dokumenta'],['partner','Primatelj'],['date','Datum slanja'],['number','Broj dokumenta'],['note','Napomena'],['project','Poslovna jedinica']]},
offers:{t:'Ponude',n:'Nova ponuda',p:'PON',s:['U izradi','Poslano','Prihvaćeno','Odbijeno','Zaključeno'],c:[['date','Datum'],['partner','Kupac'],['subject','Naslov'],['amount','Iznos'],['vat','Iznos PDV-a'],['total','Ukupno s PDV'],['currency','Valuta'],['valid','Vrijedi do']]},
incomingInvoices:{t:'Ulazni računi',n:'Novi račun',p:'URA',s:['Na knjiženju','Ovjera','Plaćeno','Knjiženo'],c:[['type','Vrsta'],['number','Br. računa'],['partner','Dobavljač'],['date','Dat. računa'],['due','Dospijeće'],['amount','Ukupno'],['currency','Valuta'],['paid','Datum plaćanja'],['project','Mjesto troška']]},
invoices:{t:'Fakture',n:'Nova faktura',p:'IFA',s:['U izradi','Knjiženo','Poslano','Storniran'],c:[['invoice','Račun broj'],['eracun','e-Račun'],['fis','Fiskalizacija'],['type','Tip'],['partner','Kupac'],['date','Datum'],['due','Dospijeće'],['amount','Ukupno'],['vat','Iznos PDV-a'],['total','Ukupno s PDV'],['currency','Valuta']]},
cash:{t:'Blagajne',n:'Otvori dnevnik',p:'BLG',s:['Otvoren','Knjiženo','Zaključeno'],c:[['date','Datum'],['partner','Dnevnik otvorio'],['opening','Početno stanje'],['income','Uplate'],['expense','Isplate'],['amount','Saldo'],['closedBy','Dnevnik zatvorio'],['closedAt','Vrijeme zaključka']]},
journal:{t:'Izravno knjiženje',n:'Novi nalog',p:'KNT',s:['U izradi','Knjiženo','Zaključeno'],c:[['date','Datum'],['type','Vrsta dok.'],['note','Opis']]},
ledger:{t:'Izvod konta',n:'Novi zapis',p:'IK',s:['Aktivan','Knjiženo'],c:[['bookDate','Dat. knjiž.'],['type','Vrsta dok.'],['docNo','Broj dokumenta'],['debit','Duguje'],['credit','Potražuje'],['analytic','Analitika'],['project','Poslovna jedinica'],['note','Opis']]},
assets:{t:'Osnovna sredstva',n:'Novo sredstvo',p:'OS',s:['Aktivno','Otpisano'],c:[['inventory','Inv. br.'],['subject','Naziv'],['registration','Registracija'],['group','Amortizacijska grupa'],['partner','Dobavljač'],['amount','Nabavna vrijednost'],['current','Ispravak vrijednosti'],['book','Knjigovodstvena vrijednost']]},
amortization:{t:'Amortizacija',n:'Nova amortizacija',p:'AM',s:['U izradi','Knjiženo','Zaključeno'],c:[['date','Datum amortizacije'],['from','Datum od'],['to','Datum do'],['amount','Ukupno']]},
closing:{t:'Zatvaranje stavaka',n:'Nova stavka',p:'ZS',s:['Otvoreno','Zatvoreno'],c:[['account','Konto'],['analytic','Analitika'],['currency','Valuta'],['debit','Otvoreno duguje'],['credit','Otvoreno potražuje'],['amount','Saldo EUR']]},
vat:{t:'PDV prijava',n:'Nova PDV prijava',p:'PDV',s:['U izradi','Knjiženo','Zaključeno'],c:[['period','Ev. br.'],['from','Datum od'],['to','Datum do'],['partner','Podnosilac'],['amount','PDV za uplatu/povrat']]},
reports:{t:'Izvještaji i obrasci',n:'Novi izvještaj',p:'IZV',s:['Spremno','U izradi'],c:[['subject','Izvještaj'],['period','Razdoblje'],['note','Opis']]},
gl:{t:'Glavna knjiga',n:'Novi zapis',p:'GK',s:['Knjiženo','Zaključeno'],c:[['account','Konto'],['subject','Naziv konta'],['debit','Duguje'],['credit','Potražuje']]},
opening:{t:'Početno stanje',n:'Novi nalog',p:'KNPS',s:['Knjiženo','Zaključeno'],c:[['date','Datum'],['type','Vrsta dok.'],['note','Opis']]},
ios:{t:'IOS',n:'Novi IOS',p:'IOS',s:['Otvoreno','Potvrđeno'],c:[['date','IOS na dan'],['partner','Dobavljač'],['amount','Saldo']]},
finalState:{t:'Završno stanje',n:'Novi nalog',p:'ZS',s:['Knjiženo','Zaključeno'],c:[['date','Datum'],['type','Vrsta dok.'],['note','Opis']]},
bank:{t:'Bankovni izvodi',n:'Novi bankovni izvod',p:'ERSTE',s:['U izradi','Knjiženo','Zaključeno'],c:[['account','Račun'],['rb','Rb'],['date','Datum'],['currency','Valuta'],['income','Uplate'],['expense','Isplate'],['amount','Dnevni saldo'],['before','Stanje prije'],['after','Stanje poslije'],['note','Bankovna referenca']]},
payments:{t:'Nalozi za plaćanje',n:'Novi bankovni nalog',p:'NP',s:['U izradi','Zaključeno'],c:[['date','Datum'],['account','Bankovni račun'],['amount','Ukupno'],['currency','Valuta'],['note','Opis naloga']]},
candidates:{t:'Kandidati',n:'Novi kandidat',p:'KAN',s:['Kandidat','Aplikant za vizu','Preuzeta viza','Odobren','Odbijen','Odustao'],c:[['partner','Prezime, Ime'],['citizenship','Državljanstvo'],['age','Dob'],['email','Email'],['phone','Broj telefona'],['city','Grad i poštanski broj'],['street','Ulica']]},
travelOrders:{t:'Putni nalozi',n:'Novi putni nalog',p:'PN',s:['U izradi','Odobreno','Zaključeno'],c:[['partner','Zaposlenik'],['from','Polazak'],['to','Povratak'],['destination','Odredište'],['amount','Trošak'],['note','Napomena']]},
leave:{t:'Godišnji odmori',n:'Novi zahtjev za GO',p:'GO',s:['Zahtjev','Odobreno','Zaključeno'],c:[['last','Prezime'],['first','Ime'],['job','Radno mjesto'],['from','Datum od'],['to','Datum do'],['days','Dana iskorišteno'],['note','Napomena']]},
leaveRights:{t:'Pravo na GO',n:'Novi obračun',p:'GOP',s:['Aktivno'],c:[['partner','Prezime, Ime'],['entitled','Pravo dana'],['used','Utrošeno dana'],['left','Preostalo dana']]},
travelPlan:{t:'Plan putovanja',n:'Dodaj',p:'PUT',s:['Planirano','U tijeku','Završeno'],c:[['type','Vrsta'],['depart','Vrijeme polaska'],['from','Mjesto polaska'],['to','Mjesto dolaska'],['arrival','Vrijeme dolaska'],['people','Osoblje'],['route','Upute']]},
hours:{t:'Radni sati',n:'Nova evidencija radnih sati',p:'SAT',s:['U izradi','Zaključeno'],c:[['project','Poslovna jedinica'],['month','Mjesec'],['year','Godina'],['hours','Sati']]},
payroll:{t:'Obračun plaća',n:'Novi obračun',p:'PL',s:['Na knjiženju','Knjiženo'],c:[['report','Oznaka izvješća'],['type','Vrsta izvješća'],['year','Godina'],['month','Mjesec'],['payDate','Datum isplate']]},
joppd:{t:'JOPPD obrasci',n:'Novi JOPPD',p:'JOPPD',s:['U izradi','Predano','Zaključeno'],c:[['report','Oznaka izvješća'],['date','Datum izvješća'],['type','Vrsta izvješća'],['people','Broj osoba'],['rows','Broj redaka'],['partner','Izvješće sastavio'],['note','Napomena']]},
contracts:{t:'Ugovori',n:'Novi ugovor',p:'UG',s:['Aktivan','Istekao','Raskinut'],c:[['type','Vrsta'],['subject','Naslov ugovora'],['partner','Partner'],['class','Klasa'],['orderNo','Urudžbeni broj'],['from','Datum od'],['to','Datum do'],['amount','Iznos']]},
companyDocs:{t:'Dokumentacija firme',n:'Novi dokument',p:'DOC',s:['Aktivno','Arhiva'],c:[['type','Vrsta'],['date','Datum dokumenta'],['note','Napomena']]},
orders:{t:'Narudžbenice',n:'Dodaj',p:'PO',s:['U izradi','Isporučeno','Zaključeno'],c:[['date','Datum'],['partner','Dobavljač'],['delivery','Datum isporuke'],['project','Poslovna jedinica'],['amount','Ukupan iznos'],['note','Napomena']]},
items:{t:'Artikli',n:'Dodaj',p:'ART',s:['Aktivan','Neaktivan'],c:[['code','Ev. br.'],['subject','Naziv robe / materijala / usluge'],['vat','PDV stopa'],['unit','JM'],['partner','Dobavljač'],['amount','Neto cijena (EUR)']]}
};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=v=>'tasker2_fixed_'+v+'_v1';
function load(v){try{const x=JSON.parse(localStorage.getItem(key(v))||'[]');if(Array.isArray(x)&&x.length)return x}catch{}return []}
function save(v,rows){localStorage.setItem(key(v),JSON.stringify(rows))}
function cls(s){return /Aktiv|Poslan|Plać|Isporuč|Odobren|Potvrđ|Spremno/.test(s)?'green':/izradi|knjiženju|Ovjera|Zahtjev|Planirano/.test(s)?'yellow':'blue'}
function render(v){const c=CFG[v];if(!c)return false;let rows=load(v);const title=document.getElementById('title'),host=document.getElementById('content');if(!host)return false;if(title)title.textContent=c.t;host.innerHTML=`<div class="toolbar"><div class="filters"><div class="project-search">⌕ <input id="fxSearch" placeholder="Pretraži ${esc(c.t.toLowerCase())}..."></div><select class="filter" id="fxStatus"><option>Sve</option>${c.s.map(x=>`<option>${esc(x)}</option>`).join('')}</select><button class="filter" id="fxExcel">Excel</button></div><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="filter" id="fxImport">↑ Uvezi dokument</button><input id="fxFile" type="file" hidden accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png"><button class="btn" id="fxNew">+ ${esc(c.n)}</button></div></div><div class="card table-card"><div style="overflow:auto"><table><thead><tr><th>Ev. br.</th><th>Status</th>${c.c.map(x=>`<th>${esc(x[1])}</th>`).join('')}<th>Dokument</th><th>Akcije</th></tr></thead><tbody id="fxBody"></tbody></table></div><div id="fxEmpty" class="project-empty" hidden>Nema zapisa. Dodaj prvi zapis.</div></div>`;
const search=document.getElementById('fxSearch'),status=document.getElementById('fxStatus'),body=document.getElementById('fxBody'),empty=document.getElementById('fxEmpty');
const draw=()=>{const q=search.value.toLowerCase().trim(),st=status.value;const data=rows.filter(r=>(st==='Sve'||r.status===st)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q)));body.innerHTML=data.map(r=>`<tr data-open="${esc(r.id)}" style="cursor:pointer"><td><b>${esc(r.id)}</b></td><td><span class="status ${cls(r.status)}">${esc(r.status)}</span></td>${c.c.map(x=>`<td>${esc(r[x[0]]||'—')}</td>`).join('')}<td>${r.fileName?'📎 '+esc(r.fileName):'—'}</td><td><div style="display:flex;gap:7px"><button class="project-edit-btn" data-edit="${esc(r.id)}">Uredi</button><button class="project-delete" data-delete="${esc(r.id)}">Obriši</button></div></td></tr>`).join('');empty.hidden=data.length>0;};
draw();search.oninput=draw;status.onchange=draw;
body.onclick=e=>{const del=e.target.closest('[data-delete]');if(del){e.stopPropagation();if(confirm('Obrisati zapis '+del.dataset.delete+'?')){rows=rows.filter(x=>x.id!==del.dataset.delete);save(v,rows);draw()}return}const edit=e.target.closest('[data-edit]');if(edit){e.stopPropagation();openForm(v,edit.dataset.edit);return}const tr=e.target.closest('[data-open]');if(tr&&v==='invoices'&&typeof window.openTaskerInvoiceDetail==='function'){const r=rows.find(x=>x.id===tr.dataset.open);if(r)window.openTaskerInvoiceDetail(r)}};
document.getElementById('fxNew').onclick=()=>openForm(v,'');document.getElementById('fxImport').onclick=()=>document.getElementById('fxFile').click();document.getElementById('fxFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r={id:c.p+'-'+Date.now().toString().slice(-6),status:c.s[0],fileName:f.name};c.c.forEach(([k])=>r[k]='');if(c.c[0])r[c.c[0][0]]=f.name;rows.unshift(r);save(v,rows);render(v)};document.getElementById('fxExcel').onclick=()=>exportCsv(c,rows);return true}
function openForm(v,id){const c=CFG[v],rows=load(v),cur=rows.find(x=>x.id===id),r=cur||{id:c.p+'-'+Date.now().toString().slice(-6),status:c.s[0],fileName:''};document.getElementById('fxOverlay')?.remove();const fields=c.c.map(([k,l])=>`<label><span>${esc(l)}</span><input id="fx_${k}" value="${esc(r[k]||'')}"></label>`).join('');document.body.insertAdjacentHTML('beforeend',`<div class="project-overlay" id="fxOverlay"><div class="project-modal"><div class="project-modal-head"><div><small>${cur?'UREĐIVANJE':'NOVI ZAPIS'}</small><h3>${esc(c.t)}</h3></div><button id="fxClose">×</button></div><div class="project-form-grid"><label><span>Evidencijski broj</span><input id="fxId" value="${esc(r.id)}"></label><label><span>Status</span><select id="fxSt">${c.s.map(x=>`<option ${r.status===x?'selected':''}>${esc(x)}</option>`).join('')}</select>${fields}<label class="wide"><span>Dokument / prilog</span><input id="fxAttach" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png"><small>${r.fileName?'Trenutno: '+esc(r.fileName):'Možeš priložiti dokument.'}</small></label></div><div class="project-modal-actions">${cur?'<button class="project-delete" id="fxDelete">Obriši</button>':'<span></span>'}<div><button class="filter" id="fxCancel">Odustani</button><button class="btn" id="fxSave">Sačuvaj</button></div></div></div></div>`);
const close=()=>document.getElementById('fxOverlay')?.remove();document.getElementById('fxClose').onclick=close;document.getElementById('fxCancel').onclick=close;document.getElementById('fxSave').onclick=()=>{const o={id:document.getElementById('fxId').value.trim(),status:document.getElementById('fxSt').value,fileName:r.fileName||''};if(!o.id)return alert('Unesi evidencijski broj.');c.c.forEach(([k])=>o[k]=document.getElementById('fx_'+k).value.trim());const f=document.getElementById('fxAttach').files[0];if(f)o.fileName=f.name;const out=cur?rows.map(x=>x.id===id?o:x):[o,...rows];save(v,out);close();render(v)};if(cur)document.getElementById('fxDelete').onclick=()=>{if(confirm('Obrisati zapis '+cur.id+'?')){save(v,rows.filter(x=>x.id!==cur.id));close();render(v)}}}
function exportCsv(c,rows){const all=[['Ev. br.','Status',...c.c.map(x=>x[1]),'Dokument'],...rows.map(r=>[r.id,r.status,...c.c.map(x=>r[x[0]]||''),r.fileName||''])];const text=all.map(a=>a.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(';')).join('\n');const blob=new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=c.t+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const previous=window.show;window.show=function(v){if(CFG[v])return render(v);return typeof previous==='function'?previous(v):undefined};document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b&&CFG[b.dataset.view]){e.preventDefault();setTimeout(()=>render(b.dataset.view),0)}});
window.taskerFixedModules=CFG;
})();