(()=>{
const MODULES={
outgoing:{title:'Izlazna pošta',newLabel:'Nova pošta',prefix:'IP',fields:['partner','date','subject','project'],labels:{partner:'Primatelj',date:'Datum slanja',subject:'Broj / predmet dokumenta',project:'Poslovna jedinica'},seed:[['Hrvatska poštanska banka d.d.','23.07.2026','Upitnik za klijente','Uprava'],['LAZZZ d.o.o.','21.07.2026','Poziv na plaćanje','LAZZZ Ravna Gora']]},
offers:{title:'Ponude',newLabel:'Nova ponuda',prefix:'PON',fields:['partner','date','subject','amount'],labels:{partner:'Kupac',date:'Datum',subject:'Naslov',amount:'Iznos'},seed:[['CTBA d.o.o.','21.11.2025','Ponuda 2025-2','0,00 €'],['Klarnest d.o.o.','14.11.2025','Ponuda 2025-1','0,00 €']]},
incomingInvoices:{title:'Ulazni računi',newLabel:'Novi račun',prefix:'URA',fields:['partner','date','subject','amount','project'],labels:{partner:'Dobavljač',date:'Datum računa',subject:'Broj računa',amount:'Ukupno',project:'Mjesto troška'},seed:[['TOI TOI d.o.o.','13.08.2026','19315-1-1','106,25 €','Kuća Čolak'],['RADNIK USLUGE d.o.o.','12.08.2026','698-1-1','375,00 €','Smještaj']]},
invoices:{title:'Fakture',newLabel:'Nova faktura',prefix:'IFA',fields:['partner','date','subject','amount','project'],labels:{partner:'Kupac',date:'Datum',subject:'Račun broj',amount:'Ukupno s PDV',project:'Poslovna jedinica'},seed:[['LAZZZ d.o.o.','31.07.2026','14-1-1','57.638,26 €','LAZZZ Ravna Gora'],['LAZZZ d.o.o.','27.07.2026','13-1-1','360.000,00 €','LAZZZ Ravna Gora']]},
cash:{title:'Blagajne',newLabel:'Novi dnevnik',prefix:'BLG',fields:['partner','date','amount','note'],labels:{partner:'Dnevnik otvorio',date:'Datum',amount:'Saldo',note:'Napomena'},seed:[['Nikolina Lozančić','30.07.2026','-224,34 €','Dnevna blagajna'],['Ivana Tokić','29.06.2026','385,66 €','Dnevna blagajna']]},
journal:{title:'Izravno knjiženje',newLabel:'Novi nalog',prefix:'KNT',fields:['date','subject','note','project'],labels:{date:'Datum',subject:'Vrsta dokumenta',note:'Opis',project:'Poslovna jedinica'},seed:[['31.07.2026','Temeljnica','Korekcija plaće za radnike','Uprava'],['28.07.2026','Temeljnica','Plaće isplaćene sa Constructiona','Uprava']]},
ledger:{title:'Izvod konta',newLabel:'Novi zapis',prefix:'IK',fields:['subject','partner','amount','note'],labels:{subject:'Konto',partner:'Analitika',amount:'Saldo',note:'Opis'},seed:[['2200','Dobavljači dobara','203,23 €','Otvorena stavka'],['4130','Troškovi registracije','85,39 €','Knjiženje']]},
assets:{title:'Osnovna sredstva',newLabel:'Novo sredstvo',prefix:'OS',fields:['subject','partner','date','amount','note'],labels:{subject:'Naziv',partner:'Dobavljač',date:'Datum nabave',amount:'Nabavna vrijednost',note:'Registracija / napomena'},seed:[['Kombi vozilo','Demo dobavljač','12.01.2025','24.500,00 €','ZG demo'],['Hilti alat','Demo dobavljač','03.03.2026','1.250,00 €','Alat']]},
vat:{title:'PDV prijava',newLabel:'Nova PDV prijava',prefix:'PDV',fields:['date','subject','amount','partner'],labels:{date:'Razdoblje',subject:'Vrsta',amount:'PDV za uplatu/povrat',partner:'Podnosilac'},seed:[['06/2026','PDV prijava','-1.703,84 €','Mario Lozančić'],['05/2026','PDV prijava','-771,52 €','Mario Lozančić']]},
gl:{title:'Glavna knjiga',newLabel:'Novi zapis',prefix:'GK',fields:['subject','partner','amount','note'],labels:{subject:'Konto',partner:'Naziv konta',amount:'Duguje / Potražuje',note:'Opis'},seed:[['4130','Trošak registracije','12,98 €','Knjiženje'],['2200','Dobavljači dobara','203,23 €','Knjiženje']]},
bank:{title:'Bankovni izvodi',newLabel:'Novi bankovni izvod',prefix:'ERSTE',fields:['date','subject','amount','note'],labels:{date:'Datum',subject:'Račun / banka',amount:'Dnevni saldo',note:'Bankovna referenca'},seed:[['09.07.2026','ERSTE','-11,06 €','CAMT053/11'],['08.07.2026','ERSTE','-2,06 €','CAMT053/11']]},
payments:{title:'Nalozi za plaćanje',newLabel:'Novi bankovni nalog',prefix:'NP',fields:['date','subject','amount','note'],labels:{date:'Datum',subject:'Bankovni račun',amount:'Ukupno',note:'Opis naloga'},seed:[['27.07.2026','ERSTE','24.686,75 €','Plaće i davanja za 5/2026'],['29.05.2026','ERSTE','56.638,72 €','Plaće i davanja']]},
candidates:{title:'Kandidati',newLabel:'Novi kandidat',prefix:'KAN',fields:['partner','subject','date','note'],labels:{partner:'Prezime i ime',subject:'Državljanstvo',date:'Datum prijave',note:'Telefon / napomena'},seed:[['Protić, Dragan','Srbija','18.08.2026','Kandidat'],['Gajmer, Neesha','Nepal','17.08.2026','Kandidat']]},
leave:{title:'Godišnji odmori',newLabel:'Novi zahtjev za GO',prefix:'GO',fields:['partner','date','subject','note'],labels:{partner:'Zaposlenik',date:'Datum od',subject:'Datum do',note:'Dani / napomena'},seed:[['Jonić Stefan','24.08.2026','04.09.2026','10 dana'],['Tokić Ivana','12.06.2026','15.06.2026','2 dana']]},
hours:{title:'Radni sati',newLabel:'Nova evidencija radnih sati',prefix:'SAT',fields:['project','date','subject','amount'],labels:{project:'Poslovna jedinica',date:'Mjesec / godina',subject:'Zaposlenik / opis',amount:'Sati'},seed:[['Kuća Čolak','07/2026','Evidencija radnih sati','184 h'],['Pajić - Amerikanac','07/2026','Evidencija radnih sati','172 h']]},
payroll:{title:'Obračun plaća',newLabel:'Novi obračun',prefix:'PL',fields:['date','subject','amount','note'],labels:{date:'Mjesec / godina',subject:'Vrsta izvješća',amount:'Broj osoba',note:'Datum isplate'},seed:[['07/2026','Izvorni','18 osoba','10.08.2026'],['06/2026','Izvorni','22 osobe','06.07.2026']]},
joppd:{title:'JOPPD obrasci',newLabel:'Novi JOPPD',prefix:'JOPPD',fields:['date','subject','amount','partner'],labels:{date:'Datum izvješća',subject:'Oznaka izvješća',amount:'Broj osoba',partner:'Izvješće sastavio'},seed:[['10.08.2026','26222','18','Nikolina Lozančić'],['06.07.2026','26187','22','Nikolina Lozančić']]},
contracts:{title:'Ugovori',newLabel:'Novi ugovor',prefix:'UG',fields:['partner','date','subject','amount','project'],labels:{partner:'Partner',date:'Datum od',subject:'Naslov ugovora',amount:'Iznos',project:'Klasa / poslovna jedinica'},seed:[['VERTIV CROATIA d.o.o.','22.07.2026','Oblaganje modula','219.000 €','VERTIV'],['DNB','31.05.2026','Raskid ugovora','0 €','Uprava']]},
companyDocs:{title:'Dokumentacija firme',newLabel:'Novi dokument',prefix:'DOC',fields:['date','subject','note','partner'],labels:{date:'Datum dokumenta',subject:'Vrsta',note:'Napomena',partner:'Izdavatelj'},seed:[['01.06.2026','Odluka','Izvadak iz sudskog registra','Sudski registar'],['01.02.2025','Odluka','Pravilnik o radu','Interno']]},
orders:{title:'Narudžbenice',newLabel:'Nova narudžbenica',prefix:'PO',fields:['partner','date','amount','project','note'],labels:{partner:'Dobavljač',date:'Datum',amount:'Ukupan iznos',project:'Poslovna jedinica',note:'Napomena'},seed:[['Bačelić d.o.o.','29.10.2025','57,90 €','Kuća Čolak','Pretponuda'],['WÜRTH-HRVATSKA d.o.o.','27.10.2025','691,74 €','Kuća Čolak','Ponuda']]},
items:{title:'Artikli',newLabel:'Novi artikl',prefix:'ART',fields:['subject','partner','amount','note'],labels:{subject:'Naziv robe / materijala / usluge',partner:'Dobavljač',amount:'Neto cijena',note:'JM / PDV / napomena'},seed:[['FOLIJA ZAŠTITNA 50 m2','Bačelić d.o.o.','11,26 €','KOM • PDV 25%'],['VALJAK 25 CM','Bačelić d.o.o.','6,91 €','KOM • PDV 25%']]}
};
const FIELD_ORDER=['partner','date','subject','amount','project','note'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=v=>'tasker2_module_'+v+'_v1';
function getRows(v){let r;try{r=JSON.parse(localStorage.getItem(key(v))||'null')}catch(e){}if(Array.isArray(r))return r;const c=MODULES[v];return c.seed.map((a,i)=>({id:`${c.prefix}-${String(i+1).padStart(3,'0')}`,status:i?'Zaključeno':'Aktivan',...Object.fromEntries(c.fields.map((f,n)=>[f,a[n]||''])),fileName:''}))}
function save(v,rows){localStorage.setItem(key(v),JSON.stringify(rows))}
function statusClass(s){return s==='Aktivan'?'green':s==='Čeka ovjeru'?'yellow':'blue'}
function render(v){const c=MODULES[v];if(!c)return;const host=document.getElementById('content'),title=document.getElementById('title');if(title)title.textContent=c.title;let rows=getRows(v);host.innerHTML=`<div class="toolbar"><div class="filters"><div class="project-search">⌕ <input id="modSearch" placeholder="Pretraži ${esc(c.title.toLowerCase())}..."></div><select class="filter" id="modStatus"><option>Sve</option><option>Aktivan</option><option>Zaključeno</option></select><button class="filter" id="modExcel">Excel</button></div><div style="display:flex;gap:10px"><button class="filter" id="modImport">↑ Uvezi dokument</button><input id="modFile" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" hidden><button class="btn" id="modNew">+ ${esc(c.newLabel)}</button></div></div><div class="card table-card"><table><thead><tr><th>Ev. br.</th><th>Status</th>${c.fields.filter(f=>f!=='note').map(f=>`<th>${esc(c.labels[f]||f)}</th>`).join('')}<th>Dokument</th><th>Akcije</th></tr></thead><tbody id="modRows"></tbody></table><div id="modEmpty" class="project-empty" hidden>Nema zapisa.</div></div>`;
const draw=()=>{const q=document.getElementById('modSearch').value.toLowerCase().trim(),st=document.getElementById('modStatus').value;const data=rows.filter(r=>(st==='Sve'||r.status===st)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q)));document.getElementById('modRows').innerHTML=data.map(r=>`<tr><td><b>${esc(r.id)}</b></td><td><span class="status ${statusClass(r.status)}">${esc(r.status)}</span></td>${c.fields.filter(f=>f!=='note').map(f=>`<td>${esc(r[f]||'—')}</td>`).join('')}<td>${r.fileName?'📎 '+esc(r.fileName):'—'}</td><td><div style="display:flex;gap:7px"><button class="project-edit-btn" data-edit="${esc(r.id)}">Uredi</button><button class="project-delete" data-delete="${esc(r.id)}" style="padding:8px 11px">Obriši</button></div></td></tr>`).join('');document.getElementById('modEmpty').hidden=data.length>0;document.getElementById('modRows').onclick=e=>{const d=e.target.closest('[data-delete]');if(d){if(confirm(`Obrisati zapis ${d.dataset.delete}?`)){rows=rows.filter(x=>x.id!==d.dataset.delete);save(v,rows);draw()}return}const ed=e.target.closest('[data-edit]');if(ed)form(v,ed.dataset.edit,()=>{rows=getRows(v);render(v)})}};
draw();document.getElementById('modSearch').oninput=draw;document.getElementById('modStatus').onchange=draw;document.getElementById('modNew').onclick=()=>form(v,'',()=>render(v));document.getElementById('modImport').onclick=()=>document.getElementById('modFile').click();document.getElementById('modFile').onchange=e=>{const f=e.target.files[0];if(!f)return;rows.unshift({id:`${c.prefix}-${Date.now().toString().slice(-6)}`,status:'Aktivan',partner:f.name,date:new Date().toLocaleDateString('hr-HR'),subject:'Uvezeni dokument',amount:'',project:'',note:'Uvezen dokument',fileName:f.name,fileType:f.type});save(v,rows);render(v)};document.getElementById('modExcel').onclick=()=>exportCsv(c,rows)}
function form(v,id,onDone){const c=MODULES[v],rows=getRows(v),cur=rows.find(x=>x.id===id),r=cur||{id:`${c.prefix}-${Date.now().toString().slice(-6)}`,status:'Aktivan',fileName:''};document.getElementById('moduleOverlay')?.remove();const inputs=c.fields.map(f=>`<label class="${f==='note'?'wide':''}"><span>${esc(c.labels[f]||f)}</span>${f==='note'?`<textarea id="mf_${f}" rows="4">${esc(r[f]||'')}</textarea>`:`<input id="mf_${f}" value="${esc(r[f]||'')}">`}</label>`).join('');document.body.insertAdjacentHTML('beforeend',`<div class="project-overlay" id="moduleOverlay"><div class="project-modal"><div class="project-modal-head"><div><small>${cur?'UREĐIVANJE':'NOVI ZAPIS'}</small><h3>${esc(c.title)}</h3></div><button id="moduleClose">×</button></div><div class="project-form-grid"><label><span>Evidencijski broj</span><input id="mf_id" value="${esc(r.id)}"></label><label><span>Status</span><select id="mf_status"><option ${r.status==='Aktivan'?'selected':''}>Aktivan</option><option ${r.status==='Zaključeno'?'selected':''}>Zaključeno</option></select></label>${inputs}<label class="wide"><span>Dokument</span><input id="mf_file" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png"><small>${r.fileName?'Trenutno: '+esc(r.fileName):'PDF, Word, Excel ili slika'}</small></label></div><div class="project-modal-actions">${cur?'<button class="project-delete" id="moduleDelete">Obriši</button>':'<span></span>'}<div><button class="filter" id="moduleCancel">Odustani</button><button class="btn" id="moduleSave">Sačuvaj</button></div></div></div></div>`);const close=()=>document.getElementById('moduleOverlay')?.remove();document.getElementById('moduleClose').onclick=close;document.getElementById('moduleCancel').onclick=close;document.getElementById('moduleSave').onclick=()=>{const newId=document.getElementById('mf_id').value.trim();if(!newId){alert('Unesi evidencijski broj.');return}const data={id:newId,status:document.getElementById('mf_status').value};c.fields.forEach(f=>data[f]=document.getElementById('mf_'+f).value.trim());const file=document.getElementById('mf_file').files[0];data.fileName=file?file.name:(r.fileName||'');data.fileType=file?(file.type||''):(r.fileType||'');let out=getRows(v);if(cur)out=out.map(x=>x.id===id?data:x);else out.unshift(data);save(v,out);close();onDone()};if(cur)document.getElementById('moduleDelete').onclick=()=>{if(confirm(`Obrisati zapis ${cur.id}?`)){save(v,rows.filter(x=>x.id!==cur.id));close();onDone()}}}
function exportCsv(c,rows){const heads=['Ev. br.','Status',...c.fields.map(f=>c.labels[f]||f),'Dokument'];const csv=[heads.join(';'),...rows.map(r=>[r.id,r.status,...c.fields.map(f=>r[f]||''),r.fileName||''].map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(';'))].join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=c.title.toLowerCase().replace(/\s+/g,'-')+'.csv';a.click();URL.revokeObjectURL(a.href)}
window.taskerModules=MODULES;const oldShow=window.show;if(typeof oldShow==='function')window.show=function(v){if(MODULES[v])return render(v);return oldShow(v)};document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b&&MODULES[b.dataset.view])setTimeout(()=>render(b.dataset.view),0)});
})();