(()=>{
const M={
outgoing:{title:'Izlazna pošta',newLabel:'Nova pošta',prefix:'IP',statuses:['U izradi','Poslano','Zaključeno'],cols:[['type','Vrsta dokumenta'],['partner','Primatelj'],['date','Datum slanja'],['number','Broj dokumenta'],['note','Napomena'],['project','Poslovna jedinica']],seed:[['Dopis','Hrvatska poštanska banka d.d.','23.07.2026','Upitnik za klijente','Poslano klijentu','Uprava'],['Dopis','LAZZZ d.o.o.','21.07.2026','Poziv na plaćanje','Rok 8 dana','LAZZZ Ravna Gora']]},
offers:{title:'Ponude',newLabel:'Nova ponuda',prefix:'PON',statuses:['U izradi','Poslano','Prihvaćeno','Odbijeno','Zaključeno'],cols:[['date','Datum'],['partner','Kupac'],['subject','Naslov'],['amount','Iznos'],['vat','Iznos PDV-a'],['total','Ukupno s PDV'],['currency','Valuta'],['valid','Vrijedi do']],seed:[['21.11.2025','TASKER d.o.o.','Ponuda 2025-2','0,00','0,00','0,00','EUR','24.12.2025'],['14.11.2025','Klarnest d.o.o.','Ponuda 2025-1','0,00','0,00','0,00','EUR','14.12.2025']]},
incomingInvoices:{title:'Ulazni računi',newLabel:'Novi račun',prefix:'URA',statuses:['Na knjiženju','Ovjera','Plaćeno','Knjiženo'],extra:'Uvoz računa',cols:[['type','Vrsta'],['number','Br. računa'],['partner','Dobavljač'],['date','Dat. računa'],['due','Dospijeće'],['amount','Ukupno'],['currency','Valuta'],['paid','Datum plaćanja'],['project','Mjesto troška']],seed:[['URA','19315-1-1','TOI TOI d.o.o.','13.08.2026','21.08.2026','106,25','EUR','','Kuća Čolak'],['URA','698-1-1','RADNIK USLUGE d.o.o.','12.08.2026','22.08.2026','375,00','EUR','','Smještaj']]},
invoices:{title:'Fakture',newLabel:'Nova faktura',prefix:'IFA',statuses:['U izradi','Knjiženo','Poslano','Storniran'],cols:[['invoice','Račun broj'],['eracun','e-Račun'],['fis','Fiskalizacija'],['type','Tip'],['partner','Kupac'],['date','Datum'],['due','Dospijeće'],['amount','Ukupno'],['vat','Iznos PDV-a'],['total','Ukupno s PDV'],['currency','Valuta']],seed:[['14-1-1','POSLANO','✓','RN','LAZZZ d.o.o.','31.07.2026','15.09.2026','57.638,26','0,00','57.638,26','EUR'],['13-1-1','POSLANO','✓','RN','LAZZZ d.o.o.','27.07.2026','27.07.2026','360.000,00','0,00','360.000,00','EUR']]},
cash:{title:'Blagajne',newLabel:'Otvori dnevnik',prefix:'BLG',statuses:['Otvoren','Knjiženo','Zaključeno'],cols:[['date','Datum'],['partner','Dnevnik otvorio'],['opening','Početno stanje'],['income','Uplate'],['expense','Isplate'],['amount','Saldo'],['closedBy','Dnevnik zatvorio'],['closedAt','Vrijeme zaključka']],seed:[['30.07.2026','Nikolina Lozančić','-324,34','1.700,00','1.600,00','-224,34','',''],['29.07.2026','Nikolina Lozančić','-324,34','4.000,00','4.000,00','-324,34','Nikolina Lozančić','30.07.2026 11:05']]},
journal:{title:'Izravno knjiženje',newLabel:'Novi nalog',prefix:'KNT',statuses:['U izradi','Knjiženo','Zaključeno'],cols:[['date','Datum'],['type','Vrsta dok.'],['note','Opis']],seed:[['31.07.2026','Temeljnica','Korekcija plaće za radnike koji nisu radili'],['28.07.2026','Temeljnica','Plaće isplaćene sa Constructiona']]},
ledger:{title:'Izvod konta',newLabel:'Novi zapis',prefix:'IK',statuses:['Aktivan','Knjiženo'],filters:true,cols:[['bookDate','Dat. knjiž.'],['type','Vrsta dok.'],['docNo','Broj dokumenta'],['debit','Duguje'],['credit','Potražuje'],['analytic','Analitika'],['project','Poslovna jedinica'],['note','Opis']],seed:[['31.07.2026','URA','19315-1-1','203,23','0,00','2200','Uprava','Dobavljači dobara'],['31.07.2026','TEM','KNT-2026-35','0,00','203,23','2200','Uprava','Zatvaranje stavke']]},
assets:{title:'Osnovna sredstva',newLabel:'Novo sredstvo',prefix:'OS',statuses:['Aktivno','Otpisano'],cols:[['inventory','Inv. br.'],['subject','Naziv'],['registration','Registracija'],['group','Amortizacijska grupa'],['partner','Dobavljač'],['amount','Nabavna vrijednost'],['current','Ispravak vrijednosti'],['book','Knjigovodstvena vrijednost']],seed:[['OS-001','VW Transporter','ZG demo','Vozila','Demo dobavljač','24.500,00','8.500,00','16.000,00'],['OS-002','Hilti alat','','Alati','Demo dobavljač','1.250,00','312,50','937,50']]},
amortization:{title:'Amortizacija',newLabel:'Nova amortizacija',prefix:'AM',statuses:['U izradi','Knjiženo','Zaključeno'],cols:[['date','Datum amortizacije'],['from','Datum od'],['to','Datum do'],['amount','Ukupno']],seed:[['31.12.2025','01.01.2025','31.12.2025','15.231,76']]},
closing:{title:'Zatvaranje stavaka',newLabel:'Nova stavka',prefix:'ZS',statuses:['Otvoreno','Zatvoreno'],filters:true,cols:[['account','Konto'],['analytic','Analitika'],['currency','Valuta'],['debit','Otvoreno duguje'],['credit','Otvoreno potražuje'],['debitEur','Duguje EUR'],['creditEur','Potražuje EUR'],['amount','Saldo EUR']],seed:[['2200','Bačelić d.o.o.','EUR','3.041,59','0,00','3.041,59','0,00','3.041,59'],['1200','LAZZZ d.o.o.','EUR','0,00','57.638,26','0,00','57.638,26','-57.638,26']]},
vat:{title:'PDV prijava',newLabel:'Nova PDV prijava',prefix:'PDV',statuses:['U izradi','Knjiženo','Zaključeno'],cols:[['period','Ev. br.'],['from','Datum od'],['to','Datum do'],['partner','Podnosilac'],['amount','PDV za uplatu/povrat']],seed:[['06/2026','01.06.2026','30.06.2026','Mario Lozančić','-1.703,84'],['05/2026','01.05.2026','31.05.2026','Mario Lozančić','-771,52']]},
reports:{title:'Izvještaji i obrasci',newLabel:'Novi izvještaj',prefix:'IZV',statuses:['Spremno','U izradi'],reports:true,cols:[['subject','Izvještaj'],['period','Razdoblje'],['note','Opis']],seed:[['Bruto bilanca','2026','Pregled bruto bilance'],['Izvod konta','2026','Promet po kontima'],['Izvještaj o dospijeću obveza i potraživanja','2026','Dospjele stavke'],['Izvod otvorenih stavaka','2026','Otvorene stavke'],['E-izvještavanje o naplati','2026','Naplata'],['Saldakonti','2026','Partneri'],['Sintetika po kontima','2026','Konta'],['Dnevnik knjiženja','2026','Knjiženja'],['Dokumenti glavne knjige','2026','Dokumenti']]},
gl:{title:'Glavna knjiga',newLabel:'Novi zapis',prefix:'GK',statuses:['Knjiženo','Zaključeno'],cols:[['account','Konto'],['subject','Naziv konta'],['debit','Duguje'],['credit','Potražuje'],['debitEur','Duguje EUR'],['creditEur','Potražuje EUR']],seed:[['4130','50% troška registracije osobnih automobila','12,98','0,00','12,98','0,00'],['2200','Dobavljači dobara','0,00','203,23','0,00','203,23']]},
opening:{title:'Početno stanje',newLabel:'Novi nalog',prefix:'KNPS',statuses:['Knjiženo','Zaključeno'],cols:[['date','Datum'],['type','Vrsta dok.'],['note','Opis']],seed:[['01.01.2026','Temeljnica početnog stanja','Početno stanje 2026'],['01.01.2025','Temeljnica početnog stanja','Početno stanje 2025']]},
ios:{title:'IOS',newLabel:'Novi IOS',prefix:'IOS',statuses:['Otvoreno','Potvrđeno'],cols:[['date','IOS na dan'],['partner','Dobavljač'],['amount','Saldo']],seed:[['27.04.2026','Kontrol biro d.o.o.','0,00'],['19.11.2025','ULIX d.o.o.','0,00'],['19.11.2025','Bačelić d.o.o.','0,00']]},
finalState:{title:'Završno stanje',newLabel:'Novi nalog',prefix:'ZS',statuses:['Knjiženo','Zaključeno'],cols:[['date','Datum'],['type','Vrsta dok.'],['note','Opis']],seed:[['31.12.2025','Završno stanje','Završno stanje 2025']]},
bank:{title:'Bankovni izvodi',newLabel:'Novi bankovni izvod',prefix:'ERSTE',statuses:['U izradi','Knjiženo','Zaključeno'],extra:'Učitaj SEPA datoteku',cols:[['account','Račun'],['rb','Rb'],['date','Datum'],['currency','Valuta'],['income','Uplate'],['expense','Isplate'],['amount','Dnevni saldo'],['before','Stanje prije'],['after','Stanje poslije'],['note','Bankovna referenca']],seed:[['ERSTE','42','09.07.2026','EUR','0,00','11,06','-11,06','11,06','0,00','CAMT053/11'],['ERSTE','41','08.07.2026','EUR','8.693,06','8.695,12','-2,06','13,12','11,06','CAMT053/11']]},
payments:{title:'Nalozi za plaćanje',newLabel:'Novi bankovni nalog',prefix:'NP',statuses:['U izradi','Zaključeno'],cols:[['date','Datum'],['account','Bankovni račun'],['amount','Ukupno'],['currency','Valuta'],['note','Opis naloga']],seed:[['27.07.2026','ERSTE','24.686,75','EUR','Plaće i davanja za 5/2026'],['27.07.2026','ERSTE','33.233,73','EUR','Plaće i davanja za 4/2026']]},
candidates:{title:'Kandidati',newLabel:'Novi kandidat',prefix:'ctba-2026',statuses:['Kandidat','Aplikant za vizu','Preuzeta viza','Odobren','Odbijen','Odustao'],cols:[['partner','Prezime, Ime'],['citizenship','Državljanstvo'],['age','Dob'],['email','Email'],['phone','Broj telefona'],['city','Grad i poštanski broj'],['street','Ulica']],seed:[['Protić, Dragan','Srbija','52','draganprotic74@gmail.com','+385','Šabac','Miloša Obilića'],['Gajmer, Neesha','Nepal','33','nepalinisha53@gmail.com','97477467456','Doha','']]},
leave:{title:'Godišnji odmori',newLabel:'Novi zahtjev za GO',prefix:'GO',statuses:['Zahtjev','Odobreno','Zaključeno'],cols:[['last','Prezime'],['first','Ime'],['job','Radno mjesto'],['from','Datum od'],['to','Datum do'],['days','Dana iskorišteno'],['note','Napomena']],seed:[['Jonić','Stefan','Armirač','24.08.2026','04.09.2026','10',''],['Tokić','Ivana','Administrativna služba','12.06.2026','15.06.2026','2','']]},
leaveRights:{title:'Pravo na GO',newLabel:'Novi obračun',prefix:'GO-P',statuses:['Aktivno'],cols:[['partner','Prezime, Ime'],['entitled','Pravo dana'],['used','Utrošeno dana'],['left','Preostalo dana']],seed:[['Sagar Dhawal','18','0','18'],['Ranjit Kumar Chaudhary','18','9','9'],['Deepak Kumar Kunwar','23','23','0'],['Ivana Tokić','27','18','9']]},
travelPlan:{title:'Plan putovanja',newLabel:'Dodaj',prefix:'PUT',statuses:['Planirano','U tijeku','Završeno'],cols:[['type','Vrsta'],['depart','Vrijeme polaska'],['from','Mjesto polaska'],['to','Mjesto dolaska'],['arrival','Vrijeme dolaska'],['people','Osoblje'],['route','Upute']],seed:[['Službeni put','08:00','Zagreb','Rijeka','10:15','Stefan Jonić','A6']]},
hours:{title:'Radni sati',newLabel:'Nova evidencija radnih sati',prefix:'SAT',statuses:['U izradi','Zaključeno'],cols:[['project','Poslovna jedinica'],['month','Mjesec'],['year','Godina'],['hours','Sati']],seed:[['Marko Rašić','07','2026','184'],['Smještaj','07','2026','160'],['Kuća Čolak','07','2026','172'],['Pajić - Amerikanac','07','2026','176']]},
payroll:{title:'Obračun plaća',newLabel:'Novi obračun',prefix:'PL',statuses:['Na knjiženju','Knjiženo'],cols:[['report','Oznaka izvješća'],['type','Vrsta izvješća'],['year','Godina'],['month','Mjesec'],['payDate','Datum isplate']],seed:[['26222','Izvorni','2026','07','10.08.2026'],['26187','Izvorni','2026','06','06.07.2026'],['26174','Izvorni','2026','04','23.06.2026']]},
joppd:{title:'JOPPD obrasci',newLabel:'Novi JOPPD',prefix:'JOPPD',statuses:['U izradi','Predano','Zaključeno'],cols:[['report','Oznaka izvješća'],['date','Datum izvješća'],['type','Vrsta izvješća'],['submitter','Oznaka podnositelja'],['people','Broj osoba'],['rows','Broj redaka'],['partner','Izvješće sastavio'],['note','Napomena']],seed:[['26222','10.08.2026','1','1','18','54','Nikolina Lozančić',''],['26187','06.07.2026','1','1','22','45','Nikolina Lozančić','']]},
contracts:{title:'Ugovori',newLabel:'Novi ugovor',prefix:'UG',statuses:['Aktivan','Istekao','Raskinut'],cols:[['type','Vrsta'],['subject','Naslov ugovora'],['partner','Partner'],['class','Klasa'],['orderNo','Urudžbeni broj'],['from','Datum od'],['to','Datum do'],['amount','Iznos']],seed:[['PO','Oblaganje modula za projekt','VERTIV CROATIA d.o.o.','','','22.07.2026','22.10.2026','219.000,00'],['UG.UP','Raskid ugovora i obavijest o neplaćenom dugu','DNB','','','31.05.2026','','0,00']]},
companyDocs:{title:'Dokumentacija firme',newLabel:'Novi dokument',prefix:'DOC',statuses:['Aktivno','Arhiva'],cols:[['type','Vrsta'],['date','Datum dokumenta'],['note','Napomena']],seed:[['Odluka','01.06.2026','Izvadak iz sudskog registra'],['Odluka','01.02.2025','Pravilnik o radu'],['Odluka','09.01.2026','Prijava poslovnog prostora - Fiskalizacija F1']]},
orders:{title:'Narudžbenice',newLabel:'Dodaj',prefix:'PO',statuses:['U izradi','Isporučeno','Zaključeno'],cols:[['date','Datum'],['partner','Dobavljač'],['delivery','Datum isporuke'],['project','Poslovna jedinica'],['amount','Ukupan iznos'],['note','Napomena']],seed:[['29.10.2025','Bačelić d.o.o.','30.10.2025','Kuća Čolak','57,90','Pretponuda 611922'],['27.10.2025','WÜRTH-HRVATSKA d.o.o.','28.10.2025','Kuća Čolak','691,74','Ponuda']]},
items:{title:'Artikli',newLabel:'Dodaj',prefix:'ART',statuses:['Aktivan','Neaktivan'],cols:[['code','Ev. br.'],['subject','Naziv robe / materijala / usluge'],['vat','PDV stopa'],['unit','JM'],['partner','Dobavljač'],['amount','Neto cijena (EUR)']],seed:[['10922','FOLIJA ZAŠTITNA 50 m2','25','KOM','Bačelić d.o.o.','11,26'],['10919','VALJAK 25 CM SYNTEX PROF.KOMPL','25','KOM','Bačelić d.o.o.','6,91']]}
};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=v=>'tasker2_rich_'+v+'_v2';
const getRows=v=>{let x;try{x=JSON.parse(localStorage.getItem(key(v))||'null')}catch{}if(Array.isArray(x))return x;const c=M[v];return c.seed.map((a,i)=>({id:`${c.prefix}-${String(i+1).padStart(3,'0')}`,status:c.statuses[Math.min(i,c.statuses.length-1)],fileName:'',...Object.fromEntries(c.cols.map((z,n)=>[z[0],a[n]||'']))}))};
const save=(v,r)=>localStorage.setItem(key(v),JSON.stringify(r));
const sclass=s=>/Aktiv|Plać|Poslan|Isporuč|Odobren|Spremno|Potvrđ/.test(s)?'green':/U izradi|Na knjiženju|Ovjera|Zahtjev|Planirano/.test(s)?'yellow':'blue';
function render(v){const c=M[v];if(!c)return;let rows=getRows(v);title.textContent=c.title;content.innerHTML=`<div class="toolbar"><div class="filters"><div class="project-search">⌕ <input id="mq" placeholder="Pretraži..."></div><select class="filter" id="ms"><option>Sve</option>${c.statuses.map(s=>`<option>${esc(s)}</option>`).join('')}</select>${c.filters?'<input class="filter" id="mf1" placeholder="Konto / analitika">':''}<button class="filter" id="mx">Excel</button></div><div style="display:flex;gap:10px;flex-wrap:wrap">${c.extra?`<button class="filter" id="mextra">${esc(c.extra)}</button>`:''}<button class="filter" id="mi">↑ Uvezi dokument</button><input id="mfile" type="file" hidden accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png"><button class="btn" id="mn">+ ${esc(c.newLabel)}</button></div></div><div class="card table-card"><div style="overflow:auto"><table><thead><tr><th>Ev. br.</th><th>Status</th>${c.cols.map(x=>`<th>${esc(x[1])}</th>`).join('')}<th>Dokument</th><th>Akcije</th></tr></thead><tbody id="mb"></tbody></table></div><div id="me" class="project-empty" hidden>Nema podataka.</div></div>`;
const draw=()=>{const q=mq.value.toLowerCase().trim(),st=ms.value,f=document.getElementById('mf1')?.value.toLowerCase().trim()||'';const data=rows.filter(r=>(st==='Sve'||r.status===st)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q))&&(!f||Object.values(r).join(' ').toLowerCase().includes(f)));mb.innerHTML=data.map(r=>`<tr><td><b>${esc(r.id)}</b></td><td><span class="status ${sclass(r.status)}">${esc(r.status)}</span></td>${c.cols.map(x=>`<td>${esc(r[x[0]]||'—')}</td>`).join('')}<td>${r.fileName?'📎 '+esc(r.fileName):'—'}</td><td><div style="display:flex;gap:7px"><button class="project-edit-btn" data-e="${esc(r.id)}">Uredi</button><button class="project-delete" data-d="${esc(r.id)}">Obriši</button></div></td></tr>`).join('');me.hidden=!!data.length;mb.onclick=e=>{const d=e.target.closest('[data-d]');if(d&&confirm('Obrisati zapis '+d.dataset.d+'?')){rows=rows.filter(x=>x.id!==d.dataset.d);save(v,rows);draw();return}const ed=e.target.closest('[data-e]');if(ed)form(v,ed.dataset.e)}}};
draw();mq.oninput=draw;ms.onchange=draw;if(document.getElementById('mf1'))mf1.oninput=draw;mn.onclick=()=>form(v,'');mi.onclick=()=>mfile.click();mfile.onchange=e=>{const f=e.target.files[0];if(!f)return;const r={id:`${c.prefix}-${Date.now().toString().slice(-6)}`,status:c.statuses[0],fileName:f.name};c.cols.forEach(x=>r[x[0]]='');r[c.cols[0][0]]=f.name;rows.unshift(r);save(v,rows);render(v)};mx.onclick=()=>csv(c,rows);if(document.getElementById('mextra'))mextra.onclick=()=>mfile.click();
function form(vv,id){const cur=rows.find(x=>x.id===id),r=cur||{id:`${c.prefix}-${Date.now().toString().slice(-6)}`,status:c.statuses[0],fileName:''};document.getElementById('moduleOverlay')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="project-overlay" id="moduleOverlay"><div class="project-modal"><div class="project-modal-head"><div><small>${cur?'UREĐIVANJE':'NOVI ZAPIS'}</small><h3>${esc(c.title)}</h3></div><button id="mc">×</button></div><div class="project-form-grid"><label><span>Evidencijski broj</span><input id="fid" value="${esc(r.id)}"></label><label><span>Status</span><select id="fst">${c.statuses.map(s=>`<option ${r.status===s?'selected':''}>${esc(s)}</option>`).join('')}</select></label>${c.cols.map(x=>`<label><span>${esc(x[1])}</span><input id="f_${x[0]}" value="${esc(r[x[0]]||'')}"></label>`).join('')}<label class="wide"><span>Dokument</span><input id="ff" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png"><small>${r.fileName?'Trenutno: '+esc(r.fileName):'PDF, Word, Excel ili slika'}</small></label></div><div class="project-modal-actions">${cur?'<button class="project-delete" id="fd">Obriši</button>':'<span></span>'}<div><button class="filter" id="fc">Odustani</button><button class="btn" id="fs">Sačuvaj</button></div></div></div></div>`);const close=()=>moduleOverlay.remove();mc.onclick=fc.onclick=close;fs.onclick=()=>{const o={id:fid.value.trim(),status:fst.value,fileName:r.fileName||''};if(!o.id)return alert('Unesi evidencijski broj.');c.cols.forEach(x=>o[x[0]]=document.getElementById('f_'+x[0]).value.trim());const f=ff.files[0];if(f)o.fileName=f.name;rows=cur?rows.map(x=>x.id===id?o:x):[o,...rows];save(vv,rows);close();render(vv)};if(cur)fd.onclick=()=>{if(confirm('Obrisati zapis '+cur.id+'?')){rows=rows.filter(x=>x.id!==cur.id);save(vv,rows);close();render(vv)}}}}
}
function csv(c,rows){const h=['Ev. br.','Status',...c.cols.map(x=>x[1]),'Dokument'];const body=rows.map(r=>[r.id,r.status,...c.cols.map(x=>r[x[0]]||''),r.fileName||'']);const blob=new Blob(['\ufeff'+[h,...body].map(a=>a.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(';')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=c.title+'.csv';a.click();URL.revokeObjectURL(a.href)}
window.taskerModules=M;const old=window.show;if(typeof old==='function')window.show=v=>M[v]?render(v):old(v);document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b&&M[b.dataset.view])setTimeout(()=>render(b.dataset.view),0)});
})();